### ISSUE TITLE
Fuel rods system not working properly

### ISSUE THREAD

**Issue by PzCampus** [BuiltBrokenModding/Atomic-Science#42]
Fission reactor keeps producing heat even with depleted fuel rods in it

**Comment by DarkGuardsman** [comment]
Might be the heat map not cycling over. Does it last beyond 5 mins?

**Comment by PzCampus** [comment]
Yes. It lasts beyond 5 mins. Even after restarting the map the turbines keep spinning producing power and the thermometer shows that there is heat. Newly added water start producing steam and adding/removing reactor parts doesn't make a change, the reactor keeps the depleted rod and continues to generate heat
