### ISSUE TITLE
[1.7] Recreate Ores

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/Atomic-Science#5]
- [x] Uranium Ore
- [x] World generation
- [x] Spawn settings
- [x] Enable/Disable Config

**Comment by ttamttamS** [comment]
Can I suggest not adding ores? There are plenty of mods that add basic metals and even ways to create your own. Nowadays the only thing ores are good for is disabling and replacing with your own. But that's just my experience as a modpack maker/server admin. I may not be the majority on this issue.

**Comment by DarkGuardsman** [comment]
Read the TODO list, only plan to add Uranium Ore. Which only 2-3 mods have, all of which include their own reactors.
