### ISSUE TITLE
[1.12] Holes in shoulder model for Hazmat

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/Atomic-Science#59]
As of Atomic-Science-1.12.2-3.0.6b13, holes are observed on both shoulders of the hazmat chestplate.

![image](https://user-images.githubusercontent.com/4776032/46234703-cea14480-c377-11e8-8241-6d56a368daa5.png)

**Comment by DarkGuardsman** [comment]
Duplicate https://github.com/BuiltBrokenModding/Atomic-Science/issues/3
