### ISSUE TITLE
[1.12] Radiation doesn't work on latest Forge versions

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [BuiltBrokenModding/Atomic-Science#62]
Blocks placed in worlds running recommended versions of Forge (14.23.5.2768) or above don't emit any radiation, however reloading world in older version of Forge (14.23.4.2767) fixes them.

Placing reactor core in world with Forge 14.23.5.2768 (no radiation):
![](https://feen.us/7qp006yt.png)

Reloading same world with same mods and Forge 14.23.4.2767 (core starts emitting radiation):
![](https://feen.us/9qia5j4k.png)

Mod version: 1.12.2-3.1.0b44

**Comment by DarkGuardsman** [comment]
I've had a few others report this issue as well. Still have yet to replicate it in the dev environment. Any chance you spotted errors in the console. Such as null pointer exceptions from one of the atomic science threads.

**Comment by YuRaNnNzZZ** [comment]
No errors in the log at all.
Also after several tests i've noticed that radiation can break randomly even on Forge 2767 ([log](https://gist.github.com/YuRaNnNzZZ/52d217f7ac1d2ce5d6c86ca439dbc37b)) but reloading same world in 2768 ([log](https://gist.github.com/YuRaNnNzZZ/9c3170d119fc2b5d46245b379f06528d)) somehow fixes it for already placed blocks! (but breaks again if i replace them)

**Comment by DarkGuardsman** [comment]
Strange, I tested with the dev environment and our Voltz modpack. In both cases, it worked even when removing rods and inserting them again. What I can say is try the latest alpha, if that doesn't work I'll talk you through turning on debug. That way I can see what is happening.

**Comment by YuRaNnNzZZ** [comment]
Latest build (46) with Forge 2768 (deleted configs, recreated the world) - still not working, no errors in the [log](https://gist.github.com/YuRaNnNzZZ/094063fe671abcd024ddf7ac15179c48).
![](https://feen.us/aco8eebm.png)

**Comment by DarkGuardsman** [comment]
I managed to replicate the problem with the latest forge. Going to add some debug code and hunt down the issue.

**Comment by DarkGuardsman** [comment]
Fixed in build 50 https://minecraft.curseforge.com/projects/atomic-science/files/2630719

**Comment by YuRaNnNzZZ** [comment]
Just tested, seems to be fixed. Thanks!
