### ISSUE TITLE
[Bug] [1.12.2] Disabled reactors still produce energy

### ISSUE THREAD

**Issue by VadikLeshy** [BuiltBrokenModding/Atomic-Science#69]
When reactor core is disabled with reactor controller block or even with fuel rod reaches 0 fuel, it still generates thermal energy to environment.

My config of atomic science is:
[config.zip](https://github.com/BuiltBrokenModding/Atomic-Science/files/2818161/config.zip)

Version of Atomic Science is 1.12.2-3.1.0b73

**Comment by DarkGuardsman** [comment]
Just got time to look into this, was a known issue for the last 3 months. Should be fixed in the next version...

**Comment by VadikLeshy** [comment]
> Should be fixed in the next version...

Thanks.

**Comment by VadikLeshy** [comment]
Probably it's fixed now

**Comment by DarkGuardsman** [comment]
Most likely it is, though will be doing more testing shortly.
