### ISSUE TITLE
Error in console Illegal Async Chunk Load 

### ISSUE THREAD

**Issue by Trnrr** [BuiltBrokenModding/Atomic-Science#74]
Not sure what causes this. Just got it in console and reporting it here because I think its something to do with the mod.

https://gist.github.com/Trnrr/4a13905b10efe529f7713071d730c0d4

Version: Atomic-Science-1.12.2-3.2.0b80
Minecraft: 1.12.2
SpongeForge: 1.12.2-2768-7.1.6-RC3616
Minecraft Forge: 14.23.5.2807

**Comment by DarkGuardsman** [comment]
From what I understand it can be ignored, it mostly sponge not being happy with how our threads work.

**Comment by Trnrr** [comment]
Ok thanks for the reply. I just wasn't sure if it was bad or not because it shows up in the console quite a bit.

**Comment by Trnrr** [comment]
Also just to post this here as well. I asked in the sponge discord and one of the staff said this. So it doesn't seem like it will cause too much performance issues.

> by the act of spamming to the console (IO is slow), it will cause minor performance issues
> it otherwise shouldn't cause to many issues. I have found that the stdio type of performance greatly depends on the system (and how the control panel if there is one, handles it)
