### ISSUE TITLE
Could we please get an option to disable the radiation hud in the top left? Alternatively maybe a radiation meter item instead.

### ISSUE THREAD

**Issue by brandyyn** [BuiltBrokenModding/Atomic-Science#84]

**Comment by chunkedelement** [comment]
You can disable the HUD in 1.12.2, go to game menu, mod options, select atomic science, click config on bottom, click client, then click radiation HUD, set to false to disable.

**Comment by brandyyn** [comment]
I'm on 1.7 ://

**Comment by bl4ckscor3** [comment]
We no longer update the mod for 1.7.10.

**Comment by brandyyn** [comment]
Would it not be a super simple and quick fix?

**Comment by bl4ckscor3** [comment]
Whether it is or not doesn't matter. We no longer support 1.7.10, so we won't be adding it.
